import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const tenants = sqliteTable('tenants', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  isMaster: integer('is_master', { mode: 'boolean' }).default(false),
  planId: text('plan_id'),
  settings: text('settings').default('{}'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const users = sqliteTable('users', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  email: text('email').notNull().unique(),
  name: text('name').notNull(),
  passwordHash: text('password_hash'),
  avatar: text('avatar'),
  role: text('role').default('agent').notNull(),
  permissions: text('permissions').default('[]'),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const customers = sqliteTable('customers', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone'),
  document: text('document'),
  company: text('company'),
  planId: text('plan_id'),
  status: text('status').default('active'),
  lastAccessAt: text('last_access_at'),
  tokenUsage: real('token_usage').default(0),
  voiceUsage: real('voice_usage').default(0),
  storageUsage: real('storage_usage').default(0),
  notes: text('notes'),
  tags: text('tags').default('[]'),
  maxContacts: integer('max_contacts').default(0),
  maxFlows: integer('max_flows').default(0),
  maxWorkspaces: integer('max_workspaces').default(1),
  maxPhoneNumbers: integer('max_phone_numbers').default(1),
  maxAgents: integer('max_agents').default(0),
  maxVoices: integer('max_voices').default(0),
  maxExecutions: integer('max_executions').default(0),
  maxTokens: integer('max_tokens').default(0),
  maxUsers: integer('max_users').default(1),
  maxIntegrations: integer('max_integrations').default(0),
  settings: text('settings').default('{}'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const workspaces = sqliteTable('workspaces', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  settings: text('settings').default('{}'),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const utalkIntegrations = sqliteTable('utalk_integrations', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  organizationId: text('organization_id'),
  apiTokenEncrypted: text('api_token_encrypted').notNull(),
  baseUrl: text('base_url').default('https://app-utalk.umbler.com/api'),
  status: text('status').default('disconnected'),
  lastSyncAt: text('last_sync_at'),
  createdAt: text('created_at').default('datetime("now")'),
  updatedAt: text('updated_at').default('datetime("now")'),
});

export const utalkMappings = sqliteTable('utalk_mappings', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  entityType: text('entity_type').notNull(),
  ozionEntityId: text('ozion_entity_id').notNull(),
  utalkEntityId: text('utalk_entity_id').notNull(),
  rawData: text('raw_data').default('{}'),
  createdAt: text('created_at').default('datetime("now")'),
  updatedAt: text('updated_at').default('datetime("now")'),
});

export const contacts = sqliteTable('contacts', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  waId: text('wa_id'),
  name: text('name'),
  phone: text('phone'),
  provider: text('provider').default('meta'),
  externalId: text('external_id'),
  rawProviderData: text('raw_provider_data').default('{}'),
  email: text('email'),
  avatarUrl: text('avatar_url'),
  tags: text('tags').default('[]'),
  customFields: text('custom_fields').default('{}'),
  leadSource: text('lead_source'),
  leadStatus: text('lead_status').default('new'),
  leadScore: integer('lead_score').default(0),
  leadTemperature: text('lead_temperature'),
  aiSummary: text('ai_summary'),
  utmSource: text('utm_source'),
  utmMedium: text('utm_medium'),
  utmCampaign: text('utm_campaign'),
  utmContent: text('utm_content'),
  utmTerm: text('utm_term'),
  campaignId: text('campaign_id'),
  adsetId: text('adset_id'),
  adId: text('ad_id'),
  creativeId: text('creative_id'),
  assignedTo: text('assigned_to'),
  lastMessageAt: text('last_message_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const conversations = sqliteTable('conversations', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  workspaceId: text('workspace_id'),
  contactId: text('contact_id').references(() => contacts.id).notNull(),
  provider: text('provider').default('meta'),
  externalId: text('external_id'),
  rawProviderData: text('raw_provider_data').default('{}'),
  phoneNumberId: text('phone_number_id'),
  contactWaId: text('contact_wa_id'),
  status: text('status').default('open').notNull(),
  isCtwa: integer('is_ctwa', { mode: 'boolean' }).default(false),
  ctwaClid: text('ctwa_clid'),
  adId: text('ad_id'),
  adsetId: text('adset_id'),
  campaignId: text('campaign_id'),
  creativeId: text('creative_id'),
  isAiActive: integer('is_ai_active', { mode: 'boolean' }).default(false),
  assignedTo: text('assigned_to'),
  flowId: text('flow_id'),
  startedAt: text('started_at').default('datetime("now")').notNull(),
  lastMessageAt: text('last_message_at'),
  closedAt: text('closed_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const messages = sqliteTable('messages', {
  id: text('id').primaryKey(),
  conversationId: text('conversation_id').references(() => conversations.id).notNull(),
  provider: text('provider').default('meta'),
  externalId: text('external_id'),
  rawProviderData: text('raw_provider_data').default('{}'),
  direction: text('direction').notNull(),
  type: text('type').notNull(),
  content: text('content').notNull(),
  mediaUrl: text('media_url'),
  status: text('status'),
  errorCode: integer('error_code'),
  errorMessage: text('error_message'),
  metadata: text('metadata').default('{}'),
  sentAt: text('sent_at').default('datetime("now")').notNull(),
  deliveredAt: text('delivered_at'),
  readAt: text('read_at'),
  failedAt: text('failed_at'),
});

export const messageStatusEvents = sqliteTable('message_status_events', {
  id: text('id').primaryKey(),
  messageId: text('message_id').notNull(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  provider: text('provider'),
  previousStatus: text('previous_status'),
  newStatus: text('new_status').notNull(),
  errorMessage: text('error_message'),
  errorCode: integer('error_code'),
  raw: text('raw').default('{}'),
  occurredAt: text('occurred_at').default('datetime("now")').notNull(),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const tags = sqliteTable('tags', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  name: text('name').notNull(),
  color: text('color').default('#6366f1'),
  isSystem: integer('is_system', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const customFields = sqliteTable('custom_fields', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  name: text('name').notNull(),
  type: text('type').notNull(),
  isRequired: integer('is_required', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const flows = sqliteTable('flows', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  workspaceId: text('workspace_id'),
  name: text('name').notNull(),
  description: text('description'),
  status: text('status').default('draft'),
  category: text('category'),
  isActive: integer('is_active', { mode: 'boolean' }).default(false),
  publishedAt: text('published_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const flowBlocks = sqliteTable('flow_blocks', {
  id: text('id').primaryKey(),
  flowId: text('flow_id').references(() => flows.id).notNull(),
  type: text('type').notNull(),
  label: text('label'),
  positionX: real('position_x').default(0),
  positionY: real('position_y').default(0),
  config: text('config').default('{}'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const flowEdges = sqliteTable('flow_edges', {
  id: text('id').primaryKey(),
  flowId: text('flow_id').references(() => flows.id).notNull(),
  sourceBlockId: text('source_block_id').notNull(),
  targetBlockId: text('target_block_id').notNull(),
  label: text('label'),
  condition: text('condition'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const agents = sqliteTable('agents', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  name: text('name').notNull(),
  description: text('description'),
  identity: text('identity').default('Você é um assistente virtual'),
  objective: text('objective'),
  communication: text('communication'),
  instructions: text('instructions'),
  restrictions: text('restrictions'),
  faq: text('faq').default('[]'),
  knowledgeBase: text('knowledge_base').default('[]'),
  objections: text('objections').default('[]'),
  offers: text('offers').default('[]'),
  memory: text('memory').default('{}'),
  provider: text('provider').default('openai'),
  model: text('model').default('gpt-4'),
  temperature: real('temperature').default(0.7),
  maxTokens: integer('max_tokens').default(1024),
  voiceId: text('voice_id'),
  isActive: integer('is_active', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const voices = sqliteTable('voices', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  provider: text('provider').notNull(),
  name: text('name').notNull(),
  voiceId: text('voice_id').notNull(),
  settings: text('settings').default('{}'),
  isActive: integer('is_active', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const whatsappCredentials = sqliteTable('whatsapp_credentials', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull().unique(),
  customerId: text('customer_id').references(() => customers.id),
  businessId: text('business_id'),
  businessName: text('business_name'),
  wabaId: text('waba_id'),
  wabaName: text('waba_name'),
  pageId: text('page_id'),
  phoneNumberId: text('phone_number_id'),
  displayPhoneNumber: text('display_phone_number'),
  accessTokenEncrypted: text('access_token_encrypted'),
  appId: text('app_id'),
  appSecretEncrypted: text('app_secret_encrypted'),
  webhookVerifyToken: text('webhook_verify_token'),
  phoneNumberVerified: integer('phone_number_verified', { mode: 'boolean' }).default(false),
  messagingTier: text('messaging_tier').default('UNVERIFIED'),
  qualityRating: text('quality_rating'),
  isOnBizApp: integer('is_on_biz_app', { mode: 'boolean' }).default(false),
  connectedAt: text('connected_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
  provider: text('provider').default('meta').notNull(),
  instanceName: text('instance_name'),
  evolutionApiUrl: text('evolution_api_url'),
  evolutionApiKey: text('evolution_api_key'),
});

export const integrations = sqliteTable('integrations', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  provider: text('provider').notNull(),
  name: text('name').notNull(),
  status: text('status').default('disconnected'),
  apiVersion: text('api_version'),
  credentials: text('credentials').default('{}'),
  settings: text('settings').default('{}'),
  lastCheckedAt: text('last_checked_at'),
  lastError: text('last_error'),
  isActive: integer('is_active', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const providerVersions = sqliteTable('provider_versions', {
  id: text('id').primaryKey(),
  provider: text('provider').notNull().unique(),
  currentVersion: text('current_version').notNull(),
  latestVersion: text('latest_version'),
  status: text('status').default('stable'),
  impact: text('impact'),
  changelog: text('changelog'),
  lastCheckedAt: text('last_checked_at'),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const webhooks = sqliteTable('webhooks', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  name: text('name').notNull(),
  url: text('url').notNull(),
  events: text('events').default('[]'),
  secret: text('secret'),
  status: text('status').default('active'),
  lastTriggeredAt: text('last_triggered_at'),
  lastError: text('last_error'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const webhookEvents = sqliteTable('webhook_events', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  provider: text('provider').default('meta'),
  eventId: text('event_id').notNull(),
  eventType: text('event_type').default('message'),
  payload: text('payload').default('{}'),
  rawBodyHash: text('raw_body_hash'),
  signatureValid: integer('signature_valid', { mode: 'boolean' }),
  status: text('status').default('received'),
  attempts: integer('attempts').default(1),
  errorMessage: text('error_message'),
  receivedAt: text('received_at').default('datetime("now")').notNull(),
  processedAt: text('processed_at'),
  failedAt: text('failed_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const sales = sqliteTable('sales', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  contactId: text('contact_id').references(() => contacts.id),
  conversationId: text('conversation_id'),
  product: text('product'),
  amount: real('amount'),
  currency: text('currency').default('BRL'),
  status: text('status').default('pending'),
  provider: text('provider'),
  providerSaleId: text('provider_sale_id'),
  commission: real('commission'),
  campaignId: text('campaign_id'),
  adId: text('ad_id'),
  isCtwa: integer('is_ctwa', { mode: 'boolean' }).default(false),
  metadata: text('metadata').default('{}'),
  soldAt: text('sold_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const ctwaAttributions = sqliteTable('ctwa_attributions', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  contactId: text('contact_id'),
  conversationId: text('conversation_id'),
  ctwaClid: text('ctwa_clid').notNull().unique(),
  adId: text('ad_id'),
  adsetId: text('adset_id'),
  campaignId: text('campaign_id'),
  creativeId: text('creative_id'),
  headline: text('headline'),
  body: text('body'),
  mediaType: text('media_type'),
  sourceApp: text('source_app'),
  firstMessageAt: text('first_message_at'),
  leadQualifiedAt: text('lead_qualified_at'),
  purchaseAt: text('purchase_at'),
  conversionSentToMeta: integer('conversion_sent_to_meta', { mode: 'boolean' }).default(false),
  conversionEventName: text('conversion_event_name'),
  conversionEventTime: text('conversion_event_time'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const riskWords = sqliteTable('risk_words', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  word: text('word').notNull(),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const analyticsEvents = sqliteTable('analytics_events', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  flowId: text('flow_id'),
  blockId: text('block_id'),
  event: text('event').notNull(),
  metadata: text('metadata').default('{}'),
  value: real('value'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const logs = sqliteTable('logs', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  userId: text('user_id'),
  workspaceId: text('workspace_id'),
  category: text('category').notNull(),
  action: text('action').notNull(),
  provider: text('provider'),
  status: text('status').notNull(),
  requestData: text('request_data'),
  responseData: text('response_data'),
  errorData: text('error_data'),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const systemHealth = sqliteTable('system_health', {
  id: text('id').primaryKey(),
  component: text('component').notNull().unique(),
  status: text('status').default('online').notNull(),
  message: text('message'),
  lastCheckedAt: text('last_checked_at').default('datetime("now")'),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const plans = sqliteTable('plans', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  price: real('price').default(0),
  currency: text('currency').default('BRL'),
  maxContacts: integer('max_contacts').default(0),
  maxFlows: integer('max_flows').default(0),
  maxWorkspaces: integer('max_workspaces').default(1),
  maxPhoneNumbers: integer('max_phone_numbers').default(1),
  maxAgents: integer('max_agents').default(0),
  maxVoices: integer('max_voices').default(0),
  maxExecutions: integer('max_executions').default(0),
  maxTokens: integer('max_tokens').default(0),
  maxUsers: integer('max_users').default(1),
  maxIntegrations: integer('max_integrations').default(0),
  features: text('features').default('[]'),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const subscriptions = sqliteTable('subscriptions', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').references(() => tenants.id).notNull(),
  customerId: text('customer_id').references(() => customers.id),
  planId: text('plan_id').references(() => plans.id).notNull(),
  status: text('status').default('active'),
  currentPeriodStart: text('current_period_start'),
  currentPeriodEnd: text('current_period_end'),
  canceledAt: text('canceled_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
  updatedAt: text('updated_at').default('datetime("now")').notNull(),
});

export const sessions = sqliteTable('sessions', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id).notNull(),
  token: text('token').notNull().unique(),
  expiresAt: text('expires_at').notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const auditLogs = sqliteTable('audit_logs', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  customerId: text('customer_id').references(() => customers.id),
  userId: text('user_id').references(() => users.id),
  action: text('action').notNull(),
  entity: text('entity').notNull(),
  entityId: text('entity_id'),
  oldData: text('old_data'),
  newData: text('new_data'),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const saasRevenue = sqliteTable('saas_revenue', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  customerId: text('customer_id').references(() => customers.id).notNull(),
  subscriptionId: text('subscription_id').references(() => subscriptions.id),
  planId: text('plan_id').references(() => plans.id).notNull(),
  amount: real('amount').notNull(),
  currency: text('currency').default('BRL'),
  status: text('status').default('pending'),
  paymentMethod: text('payment_method'),
  gateway: text('gateway'),
  gatewayPaymentId: text('gateway_payment_id'),
  invoiceNumber: text('invoice_number'),
  dueDate: text('due_date'),
  paidAt: text('paid_at'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const modulesEnabled = sqliteTable('modules_enabled', {
  id: text('id').primaryKey(),
  customerId: text('customer_id').references(() => customers.id).notNull(),
  moduleName: text('module_name').notNull(),
  isEnabled: integer('is_enabled', { mode: 'boolean' }).default(true),
  customSettings: text('custom_settings').default('{}'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});

export const customerUsage = sqliteTable('customer_usage', {
  id: text('id').primaryKey(),
  customerId: text('customer_id').references(() => customers.id).notNull(),
  metric: text('metric').notNull(),
  value: real('value').default(0),
  periodStart: text('period_start'),
  periodEnd: text('period_end'),
  createdAt: text('created_at').default('datetime("now")').notNull(),
});
